Task/ahh 114
uw-it-aca/uw-foodalert pull request #87
Opened 2019-06-12 17:55 UTC by KeithSRoberts

2019-06-14 20:02 UTC, KeithSRoberts commented on foodalert/static/foodalert/js/components/food-categories-template.vue
> +                this.$router.push({ name: 'notfound' });
Currently this is set to navigate to the "notfound" page as the "exit app" page has not yet been build out. Whoever builds out that page should make sure this route will switch over to the route for the new page.

2019-06-14 21:00 UTC, KumarAdi requested changes

2019-06-14 21:00 UTC, KumarAdi commented on foodalert/static/foodalert/js/components/food-categories-template.vue
> +        tooltip1: false,
We'll componentize the tooltip before we merge this one

2019-06-27 23:03 UTC, abztrakt commented
Closing this one, as #92 contains all of these commits.

2019-06-27 23:03 UTC, closed without merging